using Newtonsoft.Json; 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

// Autogenerated on : 22-6-2020 17:17:07 by afas-cli

namespace DutchGrit.Afas.BuiltIn.Entities
{
    [ConnectorName("AfasClient_FreeTableRecords")] 
    public class AfasClientFreeTableRecords : IGetEntity 
    { 

        /// <summary>
        /// Product
        /// </summary>
        [JsonProperty("Product")]
        public virtual string Product { get; set; }


        /// <summary>
        /// Tabel
        /// </summary>
        [JsonProperty("Tabel")]
        public virtual string Tabel { get; set; }


        /// <summary>
        /// Interne code
        /// </summary>
        [JsonProperty("Interne_code")]
        public virtual string Interne_code { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonProperty("Omschrijving")]
        public virtual string Omschrijving { get; set; }


        /// <summary>
        /// Tabelwaarde code
        /// </summary>
        [JsonProperty("Tabelwaarde_code")]
        public virtual string Tabelwaarde_code { get; set; }


        /// <summary>
        /// Vrije tabelwaarde
        /// </summary>
        [JsonProperty("Tabelwaarde_vrij")]
        public virtual bool? Tabelwaarde_vrij { get; set; }


        /// <summary>
        /// Geblokkeerd
        /// </summary>
        [JsonProperty("Geblokkeerd")]
        public virtual bool? Geblokkeerd { get; set; }

    }
}
