using Newtonsoft.Json; 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

// Autogenerated on : 22-6-2020 17:17:07 by afas-cli

namespace DutchGrit.Afas.Entities
{
    [ConnectorName("AfasClient_FreeTables")] 
    public class AfasClientFreeTables : IGetEntity 
    { 

        /// <summary>
        /// Product
        /// </summary>
        [JsonProperty("Product")]
        public virtual string Product { get; set; }


        /// <summary>
        /// Tabel
        /// </summary>
        [JsonProperty("Tabel")]
        public virtual string Tabel { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonProperty("Omschrijving")]
        public virtual string Omschrijving { get; set; }


        /// <summary>
        /// Lengte code
        /// </summary>
        [JsonProperty("Lengte_code")]
        public virtual int? Lengte_code { get; set; }


        /// <summary>
        /// Lengte omschrijving
        /// </summary>
        [JsonProperty("Lengte_omschrijving")]
        public virtual int? Lengte_omschrijving { get; set; }


        /// <summary>
        /// AantalRecords
        /// </summary>
        [JsonProperty("AantalRecords")]
        public virtual int? AantalRecords { get; set; }

    }
}
