using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

// Autogenerated on : 22-6-2020 17:17:08 using afas-cli.

namespace DutchGrit.Afas.Entities
{
    public class FbArticleCustom : IUpdateEntity
    {
        [JsonIgnore()]
        public IUpdateEntity[] Objects => null;
    }
}
