using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

// Autogenerated on : 22-6-2020 17:17:08 using afas-cli.

namespace DutchGrit.Afas.Entities
{
    /// <summary>
    /// Artikel
    /// </summary>
    [ConnectorName("FbItemArticle")] 
    public class FbItemArticle : IUpdateable<object>
    {
        /// <summary>
        /// Itemcode
        /// </summary>
        [JsonProperty("ItCd")]
        [MaxLength(40, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string ItCd { get; set; }

        /// <summary>
        /// Autonummering
        /// </summary>
        [JsonProperty("AuId")]
        public virtual bool? AuId { get; set; }

        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonProperty("Ds")]
        [MaxLength(100, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string Ds { get; set; }

        /// <summary>
        /// Extra omschrijving
        /// </summary>
        [JsonProperty("DsEx")]
        [MaxLength(100, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string DsEx { get; set; }

        /// <summary>
        /// Omschrijving te wijzigen
        /// </summary>
        [JsonProperty("ChDs")]
        public virtual bool? ChDs { get; set; }

        /// <summary>
        /// Artikelgroep
        /// </summary>
        [JsonProperty("Grp")]
        [MaxLength(15, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string Grp { get; set; }

        /// <summary>
        /// Locatie
        /// </summary>
        [JsonProperty("Loc")]
        [MaxLength(15, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string Loc { get; set; }

        /// <summary>
        /// Voorraad bijhouden
        /// </summary>
        [JsonProperty("BiSt")]
        public virtual bool? BiSt { get; set; }

        /// <summary>
        /// Aantal decimalen
        /// </summary>
        [JsonProperty("BiDc")]
        public virtual int? BiDc { get; set; }

        /// <summary>
        /// Basiseenheid
        /// </summary>
        [JsonProperty("BiUn")]
        [MaxLength(15, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string BiUn { get; set; }

        /// <summary>
        /// Voorkeur aanvraageenheid
        /// </summary>
        [JsonProperty("UnPR")]
        [MaxLength(15, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string UnPR { get; set; }

        /// <summary>
        /// Prijsfactor
        /// </summary>
        [JsonProperty("PrFc")]
        public virtual int? PrFc { get; set; }

        /// <summary>
        /// Land wetgeving
        /// </summary>
        [JsonProperty("CoLa")]
        [MaxLength(3, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string CoLa { get; set; }

        /// <summary>
        /// Tariefgroep
        /// </summary>
        [JsonProperty("VaRc")]
        [MaxLength(4, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaRc { get; set; }

        /// <summary>
        /// Tariefgroep bij afwijking
        /// </summary>
        [JsonProperty("VaAr")]
        [MaxLength(4, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaAr { get; set; }

        /// <summary>
        /// Dienstenberekening
        /// </summary>
        [JsonProperty("EUSe")]
        public virtual bool? EUSe { get; set; }

        /// <summary>
        /// Controle handmatige verkoop
        /// </summary>
        [JsonProperty("ChSa")]
        public virtual bool? ChSa { get; set; }

        /// <summary>
        /// Controle handmatige inkoop
        /// </summary>
        [JsonProperty("ChPu")]
        public virtual bool? ChPu { get; set; }

        /// <summary>
        /// Artikeltype
        /// </summary>
        [JsonProperty("VaTp")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaTp { get; set; }

        public static Dictionary<string, string> VaTpValues = new Dictionary<string, string>()
        {
            {"0","Standaard artikel" },
            {"1","Serienummerartikel" },
            {"2","Partijartikel" },
            {"3","1 artikeldimensie" },
            {"4","2 artikeldimensies" },
            {"5","Orderregelspecificatie" },
        };

        /// <summary>
        /// Type subartikel
        /// </summary>
        [JsonProperty("ArSu")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string ArSu { get; set; }

        public static Dictionary<string, string> ArSuValues = new Dictionary<string, string>()
        {
            {"0","Normaal Artikel" },
            {"1","Grondstof" },
            {"2","Halffabrikaat" },
            {"3","Etiket" },
            {"5","Verpakking" },
            {"6","Abonnementsartikel zonder aanschaf" },
            {"7","Abonnementsartikel met aanschaf" },
        };

        /// <summary>
        /// Itemcode verkoop
        /// </summary>
        [JsonProperty("BiSaItCd")]
        [MaxLength(40, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string BiSaItCd { get; set; }

        /// <summary>
        /// Prijsgroep
        /// </summary>
        [JsonProperty("PrGr")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string PrGr { get; set; }

        /// <summary>
        /// Prijs van
        /// </summary>
        [JsonProperty("PrFr")]
        [MaxLength(9, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string PrFr { get; set; }

        /// <summary>
        /// Verrekenprijs
        /// </summary>
        [JsonProperty("StPrice")]
        public virtual double? StPrice { get; set; }

        /// <summary>
        /// Kostprijs
        /// </summary>
        [JsonProperty("CoPrice")]
        public virtual double? CoPrice { get; set; }

        /// <summary>
        /// Verkoopprijs
        /// </summary>
        [JsonProperty("SaPrice")]
        public virtual double? SaPrice { get; set; }

        /// <summary>
        /// Inkoopprijs
        /// </summary>
        [JsonProperty("PuPrice")]
        public virtual double? PuPrice { get; set; }

        /// <summary>
        /// Consumentenprijs
        /// </summary>
        [JsonProperty("CsPrice")]
        public virtual double? CsPrice { get; set; }

        /// <summary>
        /// Ingangsdatum prijzen
        /// </summary>
        [JsonProperty("DatPri")]
        public virtual DateTime? DatPri { get; set; }

        /// <summary>
        /// Inkooprelatie
        /// </summary>
        [JsonProperty("CrId")]
        [MaxLength(16, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string CrId { get; set; }

        /// <summary>
        /// Itemcode inkooprelatie
        /// </summary>
        [JsonProperty("ItSp")]
        [MaxLength(30, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string ItSp { get; set; }

        /// <summary>
        /// Gewichtseenheid
        /// </summary>
        [JsonProperty("VaWt")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaWt { get; set; }

        public static Dictionary<string, string> VaWtValues = new Dictionary<string, string>()
        {
            {"0","Geen gewicht" },
            {"1","Microgram (µg)" },
            {"2","Milligram (mg)" },
            {"3","Gram (g)" },
            {"4","Kilogram (kg)" },
            {"5","Ton" },
        };

        /// <summary>
        /// Nettogewicht
        /// </summary>
        [JsonProperty("NeWe")]
        public virtual double? NeWe { get; set; }

        /// <summary>
        /// Brutogewicht
        /// </summary>
        [JsonProperty("GrWe")]
        public virtual double? GrWe { get; set; }

        /// <summary>
        /// CBS-gewicht
        /// </summary>
        [JsonProperty("CsWe")]
        public virtual double? CsWe { get; set; }

        /// <summary>
        /// CBS-goederencode
        /// </summary>
        [JsonProperty("CsGc")]
        [MaxLength(8, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string CsGc { get; set; }

        /// <summary>
        /// CBS-land van oorsprong
        /// </summary>
        [JsonProperty("CoOr")]
        [MaxLength(3, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string CoOr { get; set; }

        /// <summary>
        /// Aanvullende eenheid CBS
        /// </summary>
        [JsonProperty("ExUn")]
        [MaxLength(15, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string ExUn { get; set; }

        /// <summary>
        /// Aantal eenheden CBS
        /// </summary>
        [JsonProperty("CBSQuUn")]
        public virtual double? CBSQuUn { get; set; }

        /// <summary>
        /// Type barcode
        /// </summary>
        [JsonProperty("VaBc")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaBc { get; set; }

        public static Dictionary<string, string> VaBcValues = new Dictionary<string, string>()
        {
            {"0","Geen controle" },
            {"1","Barcode EAN8" },
            {"2","Barcode UPC" },
            {"3","Barcode EAN13" },
            {"4","Barcode EAN14" },
            {"5","Barcode SSCC" },
            {"6","Code 128" },
            {"7","Interleaved 2/5" },
            {"8","Interleaved 2/5 (controlegetal)" },
        };

        /// <summary>
        /// Barcode
        /// </summary>
        [JsonProperty("BaCo")]
        [MaxLength(30, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string BaCo { get; set; }

        /// <summary>
        /// Magazijntoewijzing
        /// </summary>
        [JsonProperty("WaSe")]
        public virtual bool? WaSe { get; set; }

        /// <summary>
        /// Bestelvoorstel bij verkoop
        /// </summary>
        [JsonProperty("VaCr")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaCr { get; set; }

        public static Dictionary<string, string> VaCrValues = new Dictionary<string, string>()
        {
            {"N","Nooit (geen actie bij verkooporder)" },
            {"V","Vraag stellen bij voorraadtekort" },
            {"S","Altijd vraag stellen (ongeacht voorraadtekort)" },
            {"A","Altijd (gehele orderregel loopt via inkooporder)" },
            {"R","Rest (voorraadtekort van de orderregel)" },
        };

        /// <summary>
        /// Voorraadaanvulling
        /// </summary>
        [JsonProperty("StAd")]
        public virtual bool? StAd { get; set; }

        /// <summary>
        /// Minimum voorraad
        /// </summary>
        [JsonProperty("StMi")]
        public virtual double? StMi { get; set; }

        /// <summary>
        /// Aanvullen tot
        /// </summary>
        [JsonProperty("StMa")]
        public virtual double? StMa { get; set; }

        /// <summary>
        /// Transportkosten
        /// </summary>
        [JsonProperty("TrCo")]
        public virtual double? TrCo { get; set; }

        /// <summary>
        /// Verlies (%)
        /// </summary>
        [JsonProperty("PcLo")]
        public virtual double? PcLo { get; set; }

        /// <summary>
        /// Voorraadcontrole
        /// </summary>
        [JsonProperty("StCh")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string StCh { get; set; }

        public static Dictionary<string, string> StChValues = new Dictionary<string, string>()
        {
            {"0","Controle op vrije voorraad (verkooporder en pakbon)" },
            {"1","Controle op economische voorraad (verkooporder)" },
            {"2","Controle op vrije voorraad (pakbon)" },
            {"3","Geen voorraadcontrole" },
        };

        /// <summary>
        /// Uitlevervolgorde
        /// </summary>
        [JsonProperty("VaDo")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaDo { get; set; }

        public static Dictionary<string, string> VaDoValues = new Dictionary<string, string>()
        {
            {"0","Geen uitlevervolgorde" },
            {"1","First in first out (FIFO)" },
            {"2","Last in first out (LIFO)" },
            {"3","First expired first out (FEFO)" },
        };

        /// <summary>
        /// Presentatiegroep
        /// </summary>
        [JsonProperty("PgId")]
        [MaxLength(9, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string PgId { get; set; }

        /// <summary>
        /// Gebruiken in ordertraject
        /// </summary>
        [JsonProperty("OrLi")]
        public virtual bool? OrLi { get; set; }

        /// <summary>
        /// Emballage
        /// </summary>
        [JsonProperty("PcYn")]
        public virtual bool? PcYn { get; set; }

        /// <summary>
        /// Administratie bijhouden
        /// </summary>
        [JsonProperty("AdYn")]
        public virtual bool? AdYn { get; set; }

        /// <summary>
        /// Administratie serienummers
        /// </summary>
        [JsonProperty("AdSr")]
        public virtual bool? AdSr { get; set; }

        /// <summary>
        /// Statiegeld
        /// </summary>
        [JsonProperty("PkPr")]
        public virtual double? PkPr { get; set; }

        /// <summary>
        /// Statiegeld retour
        /// </summary>
        [JsonProperty("RtPr")]
        public virtual double? RtPr { get; set; }

        /// <summary>
        /// Verwijderingsbijdrage
        /// </summary>
        [JsonProperty("DiFe")]
        public virtual bool? DiFe { get; set; }

        /// <summary>
        /// Verwijderingsbijdr. toepassen buitenl. levering
        /// </summary>
        [JsonProperty("FoDi")]
        public virtual bool? FoDi { get; set; }

        /// <summary>
        /// Bedrag verwijderingsbijdrage (excl. btw)
        /// </summary>
        [JsonProperty("DiCo")]
        public virtual double? DiCo { get; set; }

        /// <summary>
        /// Gewicht glas (gr)
        /// </summary>
        [JsonProperty("WeGl")]
        public virtual double? WeGl { get; set; }

        /// <summary>
        /// Gewicht aluminium (gr)
        /// </summary>
        [JsonProperty("WeAl")]
        public virtual double? WeAl { get; set; }

        /// <summary>
        /// Gewicht overig metaal (gr)
        /// </summary>
        [JsonProperty("WeMe")]
        public virtual double? WeMe { get; set; }

        /// <summary>
        /// Gewicht kunststof (gr)
        /// </summary>
        [JsonProperty("WePl")]
        public virtual double? WePl { get; set; }

        /// <summary>
        /// Gewicht biokunststof (gr)
        /// </summary>
        [JsonProperty("WeBp")]
        public virtual double? WeBp { get; set; }

        /// <summary>
        /// Gewicht papier/karton (gr)
        /// </summary>
        [JsonProperty("WePa")]
        public virtual double? WePa { get; set; }

        /// <summary>
        /// Gewicht hout (gr)
        /// </summary>
        [JsonProperty("WeWo")]
        public virtual double? WeWo { get; set; }

        /// <summary>
        /// Gewicht overig (gr)
        /// </summary>
        [JsonProperty("WeOt")]
        public virtual double? WeOt { get; set; }

        /// <summary>
        /// Doorbelasten
        /// </summary>
        [JsonProperty("Ch")]
        public virtual bool? Ch { get; set; }

        /// <summary>
        /// Met Transsmart uitwisselen
        /// </summary>
        [JsonProperty("ExTS")]
        public virtual bool? ExTS { get; set; }

        /// <summary>
        /// Verpakkingssoort
        /// </summary>
        [JsonProperty("PkTp")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string PkTp { get; set; }

        /// <summary>
        /// Voorkeur lengte
        /// </summary>
        [JsonProperty("QuLe")]
        public virtual double? QuLe { get; set; }

        /// <summary>
        /// Voorkeur breedte
        /// </summary>
        [JsonProperty("QuWi")]
        public virtual double? QuWi { get; set; }

        /// <summary>
        /// Voorkeur hoogte
        /// </summary>
        [JsonProperty("QuHe")]
        public virtual double? QuHe { get; set; }

        /// <summary>
        /// Stapelbaar
        /// </summary>
        [JsonProperty("Stck")]
        public virtual bool? Stck { get; set; }

        /// <summary>
        /// Geblokkeerd
        /// </summary>
        [JsonProperty("Bl")]
        public virtual bool? Bl { get; set; }

        /// <summary>
        /// Opmerking
        /// </summary>
        [JsonProperty("Rm")]
        public virtual string Rm { get; set; }

        /// <summary>
        /// Filename
        /// </summary>
        [JsonProperty("FileName")]
        [MaxLength(255, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string FileName { get; set; }

        /// <summary>
        /// File as byte-array
        /// </summary>
        [JsonProperty("FileStream")]
        public virtual byte[] FileStream { get; set; }

        /// <summary>
        /// Artikeldimensie 1
        /// </summary>
        [JsonProperty("StD1")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string StD1 { get; set; }

        /// <summary>
        /// Artikeldimensie 2
        /// </summary>
        [JsonProperty("StD2")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string StD2 { get; set; }

        /// <summary>
        /// Expiratiedatum verplicht
        /// </summary>
        [JsonProperty("EdMn")]
        public virtual bool? EdMn { get; set; }

        /// <summary>
        /// Toewijzen in verkoop
        /// </summary>
        [JsonProperty("VaAs")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaAs { get; set; }

        public static Dictionary<string, string> VaAsValues = new Dictionary<string, string>()
        {
            {"0","Geen automatische toewijzing" },
            {"1","Vraag stellen" },
            {"2","Altijd automatische toewijzing" },
        };

        /// <summary>
        /// Wachtorders toewijzen
        /// </summary>
        [JsonProperty("VaAb")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string VaAb { get; set; }

        public static Dictionary<string, string> VaAbValues = new Dictionary<string, string>()
        {
            {"0","Aantal wachtorder niet toewijzen bij automatische toewijzing" },
            {"1","Aantal wachtorder toewijzen bij automatische toewijzing" },
        };

        /// <summary>
        /// Vervangend type item
        /// </summary>
        [JsonProperty("SuIt")]
        [MaxLength(10, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string SuIt { get; set; }

        public static Dictionary<string, string> SuItValues = new Dictionary<string, string>()
        {
            {"Wst","Werksoort" },
            {"Pid","Productie-indicator" },
            {"Deg","Deeg" },
            {"Dim","Artikeldimensietotaal" },
            {"Art","Artikel" },
            {"Txt","Tekst" },
            {"Sub","Subtotaal" },
            {"Tsl","Toeslag" },
            {"Kst","Kosten" },
            {"Sam","Samenstelling" },
            {"Crs","Cursus" },
        };

        /// <summary>
        /// Vervangend artikel
        /// </summary>
        [JsonProperty("SuId")]
        [MaxLength(9, ErrorMessage = "{0} has a max of {1} characters")]
        public virtual string SuId { get; set; }

        [JsonIgnore()]
        public IUpdateEntity[] Objects
        {
            get
            {
                return _Objects.Count == 0 ? null : _Objects.ToArray();
            }
        }

        [JsonIgnore()]
        private List<IUpdateEntity> _Objects = new List<IUpdateEntity>();

        public void AddFbArticleCustom(FbArticleCustom fbarticlecustom)
        {
            this._Objects.Add(fbarticlecustom);
        }

    }
    public enum FbItemArticleVaTpValues
    {
        StandaardArtikel = 0,
        Serienummerartikel = 1,
        Partijartikel = 2,
        _1Artikeldimensie = 3,
        _2Artikeldimensies = 4,
        Orderregelspecificatie = 5,
    }

    public enum FbItemArticleArSuValues
    {
        NormaalArtikel = 0,
        Grondstof = 1,
        Halffabrikaat = 2,
        Etiket = 3,
        Verpakking = 5,
        AbonnementsartikelZonderAanschaf = 6,
        AbonnementsartikelMetAanschaf = 7,
    }

    public enum FbItemArticleVaWtValues
    {
        GeenGewicht = 0,
        MicrogramΜg = 1,
        MilligramMg = 2,
        GramG = 3,
        KilogramKg = 4,
        Ton = 5,
    }

    public enum FbItemArticleVaBcValues
    {
        GeenControle = 0,
        BarcodeEAN8 = 1,
        BarcodeUPC = 2,
        BarcodeEAN13 = 3,
        BarcodeEAN14 = 4,
        BarcodeSSCC = 5,
        Code128 = 6,
        Interleaved25 = 7,
        Interleaved25Controlegetal = 8,
    }

    public enum FbItemArticleStChValues
    {
        ControleOpVrijeVoorraadVerkooporderEnPakbon = 0,
        ControleOpEconomischeVoorraadVerkooporder = 1,
        ControleOpVrijeVoorraadPakbon = 2,
        GeenVoorraadcontrole = 3,
    }

    public enum FbItemArticleVaDoValues
    {
        GeenUitlevervolgorde = 0,
        FirstInFirstOutFIFO = 1,
        LastInFirstOutLIFO = 2,
        FirstExpiredFirstOutFEFO = 3,
    }

    public enum FbItemArticleVaAsValues
    {
        GeenAutomatischeToewijzing = 0,
        VraagStellen = 1,
        AltijdAutomatischeToewijzing = 2,
    }

    public enum FbItemArticleVaAbValues
    {
        AantalWachtorderNietToewijzenBijAutomatischeToewijzing = 0,
        AantalWachtorderToewijzenBijAutomatischeToewijzing = 1,
    }

}
