using Newtonsoft.Json; 
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

// Autogenerated on : 29-6-2020 16:43:12 by afas-cli

namespace DutchGrit.Afas.Entities
{
    [ConnectorName("Tafas_Tasks_Details")] 
    public class TafasTasksDetails : IGetEntity 
    { 

        /// <summary>
        /// Workflow
        /// </summary>
        [JsonProperty("workflow")]
        public virtual string workflow { get; set; }


        /// <summary>
        /// Taak
        /// </summary>
        [JsonProperty("task")]
        public virtual string task { get; set; }


        /// <summary>
        /// Doorlooptijd
        /// </summary>
        [JsonProperty("run_time")]
        public virtual double? run_time { get; set; }


        /// <summary>
        /// Gedelegeerd door
        /// </summary>
        [JsonProperty("delegated_by")]
        public virtual string delegated_by { get; set; }


        /// <summary>
        /// Gedelegeerd aan
        /// </summary>
        [JsonProperty("delegated_to")]
        public virtual string delegated_to { get; set; }


        /// <summary>
        /// Overgedragen door
        /// </summary>
        [JsonProperty("transferred_by")]
        public virtual string transferred_by { get; set; }


        /// <summary>
        /// Overgedragen aan
        /// </summary>
        [JsonProperty("transferred_to")]
        public virtual string transferred_to { get; set; }


        /// <summary>
        /// Workflowtaakmanager
        /// </summary>
        [JsonProperty("_SU")]
        public virtual bool? _SU { get; set; }


        /// <summary>
        /// GUID Workflow
        /// </summary>
        [JsonProperty("guid_workflow")]
        public virtual string guid_workflow { get; set; }


        /// <summary>
        /// GUID taak
        /// </summary>
        [JsonProperty("guid_task")]
        public virtual string guid_task { get; set; }


        /// <summary>
        /// GUID
        /// </summary>
        [JsonProperty("guid")]
        public virtual int? guid { get; set; }


        /// <summary>
        /// Nummer dossieritem
        /// </summary>
        [JsonProperty("number")]
        public virtual int? number { get; set; }


        /// <summary>
        /// Type dossieritem
        /// </summary>
        [JsonProperty("subjecttype")]
        public virtual int? subjecttype { get; set; }


        /// <summary>
        /// Type dossieritem omschrijving
        /// </summary>
        [JsonProperty("subjecttype_description")]
        public virtual string subjecttype_description { get; set; }


        /// <summary>
        /// Onderwerp
        /// </summary>
        [JsonProperty("title")]
        public virtual string title { get; set; }


        /// <summary>
        /// Toelichting
        /// </summary>
        [JsonProperty("description")]
        public virtual string description { get; set; }


        /// <summary>
        /// Instuurdatum
        /// </summary>
        [JsonProperty("submitdate")]
        public virtual DateTime? submitdate { get; set; }


        /// <summary>
        /// Begindatum
        /// </summary>
        [JsonProperty("startdate")]
        public virtual DateTime? startdate { get; set; }


        /// <summary>
        /// Einddatum
        /// </summary>
        [JsonProperty("enddate")]
        public virtual DateTime? enddate { get; set; }


        /// <summary>
        /// Afgehandeld
        /// </summary>
        [JsonProperty("handled")]
        public virtual bool? handled { get; set; }


        /// <summary>
        /// Datum afgehandeld
        /// </summary>
        [JsonProperty("date_handled")]
        public virtual DateTime? date_handled { get; set; }


        /// <summary>
        /// Bron
        /// </summary>
        [JsonProperty("source")]
        public virtual string source { get; set; }


        /// <summary>
        /// Prioriteit
        /// </summary>
        [JsonProperty("priority")]
        public virtual string priority { get; set; }


        /// <summary>
        /// Kenmerk 1
        /// </summary>
        [JsonProperty("attribute1_value")]
        public virtual string attribute1_value { get; set; }


        /// <summary>
        /// Kenmerk 2
        /// </summary>
        [JsonProperty("attribute2_value")]
        public virtual string attribute2_value { get; set; }


        /// <summary>
        /// Kenmerk 3
        /// </summary>
        [JsonProperty("attribute3_value")]
        public virtual string attribute3_value { get; set; }


        /// <summary>
        /// In workflow
        /// </summary>
        [JsonProperty("in_workflow")]
        public virtual string in_workflow { get; set; }


        /// <summary>
        /// Workflowstatus
        /// </summary>
        [JsonProperty("workflow_status")]
        public virtual string workflow_status { get; set; }


        /// <summary>
        /// Bestemming dossieritem
        /// </summary>
        [JsonProperty("destination_subject")]
        public virtual int? destination_subject { get; set; }


        /// <summary>
        /// Bestemming dossieritem onderwerp
        /// </summary>
        [JsonProperty("destination_subject_title")]
        public virtual string destination_subject_title { get; set; }


        /// <summary>
        /// Bestemming dossieritem type
        /// </summary>
        [JsonProperty("destination_subject_subjecttype")]
        public virtual string destination_subject_subjecttype { get; set; }


        /// <summary>
        /// Bestemming organisatie/persoon
        /// </summary>
        [JsonProperty("destination_organization_person")]
        public virtual int? destination_organization_person { get; set; }


        /// <summary>
        /// Bestemming organisatie/persoon soort
        /// </summary>
        [JsonProperty("destination_organization_person_sort")]
        public virtual string destination_organization_person_sort { get; set; }


        /// <summary>
        /// Bestemming organisatie/persoon naam
        /// </summary>
        [JsonProperty("destination_organization_person_name")]
        public virtual string destination_organization_person_name { get; set; }


        /// <summary>
        /// Bestemming contact
        /// </summary>
        [JsonProperty("destination_contact")]
        public virtual int? destination_contact { get; set; }


        /// <summary>
        /// Bestemming contact soort
        /// </summary>
        [JsonProperty("destination_contact_sort")]
        public virtual string destination_contact_sort { get; set; }


        /// <summary>
        /// Bestemming contact naam
        /// </summary>
        [JsonProperty("destination_contact_name")]
        public virtual string destination_contact_name { get; set; }


        /// <summary>
        /// Bestemming serienummer
        /// </summary>
        [JsonProperty("destination_serialnumber")]
        public virtual int? destination_serialnumber { get; set; }


        /// <summary>
        /// Bestemming partijnummer
        /// </summary>
        [JsonProperty("destination_lotnumber")]
        public virtual int? destination_lotnumber { get; set; }


        /// <summary>
        /// Bestemming contract
        /// </summary>
        [JsonProperty("destination_contract")]
        public virtual string destination_contract { get; set; }


        /// <summary>
        /// Bestemming project
        /// </summary>
        [JsonProperty("destination_project")]
        public virtual string destination_project { get; set; }


        /// <summary>
        /// Bestemming project omschrijving
        /// </summary>
        [JsonProperty("destination_project_description")]
        public virtual string destination_project_description { get; set; }


        /// <summary>
        /// Bestemming campagne
        /// </summary>
        [JsonProperty("destination_campaign")]
        public virtual int? destination_campaign { get; set; }


        /// <summary>
        /// Bestemming campagne omschrijving
        /// </summary>
        [JsonProperty("destination_campaign_description")]
        public virtual string destination_campaign_description { get; set; }


        /// <summary>
        /// Bestemming item
        /// </summary>
        [JsonProperty("destination_item")]
        public virtual int? destination_item { get; set; }


        /// <summary>
        /// Bestemming item omschrijving
        /// </summary>
        [JsonProperty("destination_item_description")]
        public virtual string destination_item_description { get; set; }


        /// <summary>
        /// Bestemming cursusevenement
        /// </summary>
        [JsonProperty("destination_courseevent")]
        public virtual int? destination_courseevent { get; set; }


        /// <summary>
        /// Bestemming cursusevenement omschrijving
        /// </summary>
        [JsonProperty("destination_courseevent_desscription")]
        public virtual string destination_courseevent_desscription { get; set; }


        /// <summary>
        /// Bestemming cursusevenement cursus
        /// </summary>
        [JsonProperty("destination_courseevent_course")]
        public virtual string destination_courseevent_course { get; set; }


        /// <summary>
        /// Bestemming actief
        /// </summary>
        [JsonProperty("destination_asset")]
        public virtual int? destination_asset { get; set; }


        /// <summary>
        /// Bestemming actief omschrijving
        /// </summary>
        [JsonProperty("destination_asset_description")]
        public virtual string destination_asset_description { get; set; }


        /// <summary>
        /// Bestemming abonnement
        /// </summary>
        [JsonProperty("destination_subscription")]
        public virtual int? destination_subscription { get; set; }


        /// <summary>
        /// Betreft organisatie/persoon
        /// </summary>
        [JsonProperty("concerns_organization_person")]
        public virtual bool? concerns_organization_person { get; set; }


        /// <summary>
        /// Betreft verkooprelatie
        /// </summary>
        [JsonProperty("concerns_sales_relation")]
        public virtual bool? concerns_sales_relation { get; set; }


        /// <summary>
        /// Betreft inkooprelatie
        /// </summary>
        [JsonProperty("concerns_purchase_relation")]
        public virtual bool? concerns_purchase_relation { get; set; }


        /// <summary>
        /// Betreft cliënt Vpb
        /// </summary>
        [JsonProperty("concerns_client_vpb")]
        public virtual bool? concerns_client_vpb { get; set; }


        /// <summary>
        /// Betreft werkgever
        /// </summary>
        [JsonProperty("concerns_employer")]
        public virtual bool? concerns_employer { get; set; }


        /// <summary>
        /// Betreft medewerker
        /// </summary>
        [JsonProperty("concerns_employee")]
        public virtual bool? concerns_employee { get; set; }


        /// <summary>
        /// Betreft cliënt IB
        /// </summary>
        [JsonProperty("concerns_client_ib")]
        public virtual bool? concerns_client_ib { get; set; }


        /// <summary>
        /// Betreft sollicitant
        /// </summary>
        [JsonProperty("concerns_applicant")]
        public virtual bool? concerns_applicant { get; set; }


        /// <summary>
        /// Instuurder
        /// </summary>
        [JsonProperty("submitter")]
        public virtual int? submitter { get; set; }


        /// <summary>
        /// Instuurder naam
        /// </summary>
        [JsonProperty("submitter_name")]
        public virtual string submitter_name { get; set; }


        /// <summary>
        /// Verantwoordelijke
        /// </summary>
        [JsonProperty("responsible")]
        public virtual int? responsible { get; set; }


        /// <summary>
        /// Naam verantwoordelijke
        /// </summary>
        [JsonProperty("responsible_name")]
        public virtual string responsible_name { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonProperty("attribute1")]
        public virtual string attribute1 { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonProperty("attribute2")]
        public virtual string attribute2 { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonProperty("attribute3")]
        public virtual string attribute3 { get; set; }


        /// <summary>
        /// Afbeelding
        /// </summary>
        [JsonProperty("submitter_image_id")]
        public virtual int? submitter_image_id { get; set; }


        /// <summary>
        /// Afbeelding
        /// </summary>
        [JsonProperty("responsible_image_id")]
        public virtual int? responsible_image_id { get; set; }


        /// <summary>
        /// Geopend
        /// </summary>
        [JsonProperty("opened")]
        public virtual bool? opened { get; set; }


        /// <summary>
        /// Locatie
        /// </summary>
        [JsonProperty("destination_location")]
        public virtual string destination_location { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonProperty("destination_location_description")]
        public virtual string destination_location_description { get; set; }


        /// <summary>
        /// Type
        /// </summary>
        [JsonProperty("task_type")]
        public virtual int? task_type { get; set; }


        /// <summary>
        /// Profiel
        /// </summary>
        [JsonProperty("profileid")]
        public virtual int? profileid { get; set; }


        /// <summary>
        /// Type
        /// </summary>
        [JsonProperty("profiletype")]
        public virtual int? profiletype { get; set; }


        /// <summary>
        /// Afbeelding
        /// </summary>
        [JsonProperty("destination_contact_image_id")]
        public virtual int? destination_contact_image_id { get; set; }


        /// <summary>
        /// Declaratienummer
        /// </summary>
        [JsonProperty("flex_declaration_id")]
        public virtual int? flex_declaration_id { get; set; }


        /// <summary>
        /// Dossieritem aanpassen
        /// </summary>
        [JsonProperty("edittask")]
        public virtual bool? edittask { get; set; }

    }
}
